apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postDock.name }}-secret
type: Opaque
data:
  app.db.user: {{ .Values.postgres.db.user | b64enc }}
  app.db.password: {{ .Values.postgres.db.password | b64enc }}
  app.db.cluster.replication.user: {{ .Values.postgres.replicationDb.user | b64enc }}
  app.db.cluster.replication.password: {{ .Values.postgres.replicationDb.password | b64enc }}
  app.db.pool.users: {{ .Values.pgpool.users | b64enc }}
  app.db.pool.pcp.user: {{ .Values.pgpool.pcp.user | b64enc }}
  app.db.pool.pcp.password: {{ .Values.pgpool.pcp.password | b64enc }}