apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postDock.name }}-pgpool
  labels:
    name: database-balancer
    node: pgpool
    system: {{ .Values.postDock.name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database-balancer
    node: pgpool
    system: {{ .Values.postDock.name }}