apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: mysystem
  name: mysystem-db-node1
  labels:
    name: database
    node: node1
    system: mysystem
    app: mysystem
spec:
  replicas: 1
  serviceName: "mysystem-db-node1"
  template:
    metadata:
      labels:
        name: database
        node: node1
        system: mysystem
        app: mysystem
    spec:
      containers:
        - name: mysystem-db-node1
          image: postdock/postgres:latest-postgres11-repmgr40
          imagePullPolicy: Always
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
          env:
            - name: "REPMGR_WAIT_POSTGRES_START_TIMEOUT"
              value: "600"
            - name: "PARTNER_NODES"
              value: "mysystem-db-node1-service,mysystem-db-node2-service,mysystem-db-node3-service"
            - name: "NODE_ID"
              value: "1"
            - name: "NODE_NAME"
              value: "node1"
            - name: "CLUSTER_NODE_NETWORK_NAME"
              value: "mysystem-db-node1-service"
            - name: "CONFIGS"
              value: "wal_keep_segments:250,shared_buffers:300MB,archive_command:'/bin/true'"

            # Work DB
            - name: "POSTGRES_DB"
              valueFrom:
                configMapKeyRef:
                  name: mysystem-config
                  key: app.db.database
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: mysystem-secret
                  key: app.db.user
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mysystem-secret
                  key: app.db.password

            # Cluster configs
            - name: "CLUSTER_NAME"
              valueFrom:
                configMapKeyRef:
                  name: mysystem-config
                  key: app.db.cluster.name
            - name: "REPLICATION_DB"
              valueFrom:
                configMapKeyRef:
                  name: mysystem-config
                  key: app.db.cluster.replication.db
            - name: "REPLICATION_USER"
              valueFrom:
                secretKeyRef:
                  name: mysystem-secret
                  key: app.db.cluster.replication.user
            - name: "REPLICATION_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mysystem-secret
                  key: app.db.cluster.replication.password
          ports:
            - containerPort: 5432
#          volumeMounts:
#            - mountPath:  /var/lib/postgresql/data
#              name: pg-data-volume
#      volumes:
#        - name: pg-data-volume
#          persistentVolumeClaim:
#            claimName: application-db-node1-claim