kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: application-db-node1-claim
  namespace: mysystem
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      system: application-db
      node: node1
      namespace: application-master