kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-data-mysystem-db-node-1
  namespace: mysystem
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      system: mysystem-db
      node: node-1