apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-mysystem-db-node-2
  labels:
    system: mysystem-db
    node: node-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/db-data-mysystem-db-node-2
  # awsElasticBlockStore:
  #   fsType: ext4
  #   volumeID: vol-xxxxxxx